config/routes.rb
require 'sidekiq/web'

# TODO路由测试

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'welcome#index', defaults: { format: :html }
  get 'search', to: 'search#search'

  # TODO 所有的 only: [] 全部改成 namespace :users，去掉所有的 only, except
  resources :users, only: [] do
    get :messages, on: :collection
  end

  namespace :admin, path: '/krypton' do
    authenticate :user, lambda { |u| Ability.new(u, 'Admin').can? :manage, :sidekiq } do
      mount Sidekiq::Web => '/sidekiq'
    end
    root to: redirect('/krypton/dashboard')
    resources :dashboard, :pages
    resources :newsflashes do
      member do
        patch :set_top
        patch :set_down
      end
    end
    resources :users do
      member do
        put :speak
        put :shutup
      end
      resources :posts, only: [:index], on: :collection
    end
    resources :ads, :fragment_templates
    resources :sites do
      resources :columns, module: :sites do
        patch :update_order_nums, on: :collection
      end
    end
    resources :head_lines, except: [:show] do
      get :archives, on: :collection
      post :archive, on: :member
      post :publish, on: :member
    end
    resources :columns do
      resources :posts, only: [:index], on: :collection do
        get :reviewings, on: :collection
      end
    end
    namespace :posts do
      resources :columns
    end
    resources :posts do
      resources :comments, only: [:index], on: :collection
      resources :related_links
      get :reviewings, on: :collection
      get :myown, on: :collection
      get :draft, on: :collection
      get :publish, on: :member
      post :do_publish, on: :member
      post :undo_publish, on: :member
      post :toggle_tag, on: :member
    end
    resources :favorites
    resources :comments do
      member do
        post :set_excellent
        post :do_publish
        post :do_reject
        post :undo_publish
      end
      collection do
        post :batch_do_publish
        post :batch_undo_publish
        post :batch_do_reject
        post :batch_set_excellent
        post :batch_unset_excellent
        delete :batch_destroy
      end
    end
    resources :info_flows do
      member do
        get :columns_and_ads
        post :update_columns
        post :update_ads
        get :edit_columns
        get :edit_ads
        delete :destroy_column
        delete :destroy_ad
      end
    end
    resources :mobile_ads

    get 'tools/redis'
    post 'tools/redis_refresh'
    get 'tools/report'
    post 'tools/gen_post_report'
  end

  namespace :components do
    get '/next/collections', to: 'next#collections', as: :next_collections
    get 'pages/show', to: 'pages#show', as: :page_body
    get 'posts/show', to: 'posts#show', as: :post_body
  end

  namespace :asynces do
    resources :posts, only: [] do
      get :hots, on: :collection
      get :today, on: :collection
      get :record_post_manage_session_path, on: :collection
      resources :comments, :only => [:index, :create]
    end

    resources :comments, only: [] do
      get :excellents, on: :collection
    end

    resources :favorites, only: [:create]

    resources :related_links, only: [] do
      get :get_metas_info, on: :collection
    end

    resources :head_lines, only: [] do
      get :get_metas_info, on: :collection
    end

    resources :dashboard, only: [] do
      get :charts, on: :collection
      get :pandect, on: :collection
    end

    resources :newsflashes, only: [:index]
  end

  resources :pages, only: [:show], param: :slug do
    get :hire, on: :collection
  end

  match '/current_user.json', to: 'users#current', via: :get
  match '/current_user_favorites.json', to: 'users#favorites', via: :get
  match '/upadte_current_user.json', to: 'users#update_current', via: :post
  match '/cancel_favorites', to: 'users#cancel_favorites', via: :get
  match '/comments/excellents', :controller => 'comments', :action => 'execllents', via: :get
  match '/columns/:slug/feed', :controller => 'columns', :action => 'feed', via: :get, as: :column_feed, defaults: { format: :rss }
  match '/columns/:slug(/:page)', :controller => 'columns', :action => 'show', via: :get, as: :column_slug
  match '/category/:slug(/:page)', :controller => 'columns', :action => 'show', via: :get
  match '/p/(:url_code).html' => 'posts#show', via: :get, as: :post_show_by_url_code

  match '/baidu/feed/' => 'posts#baidu_feed', via: :get, defaults: { format: :rss }
  match '/baidu/(:url_code)' => 'posts#bdnews', via: :get, as: :post_bdnews
  match '/xiaozhi/feed/' => 'posts#xiaozhi_feed', via: :get, defaults: { format: :rss }
  match '/xiaozhi/(:url_code)' => 'posts#xiaozhi_news', via: :get, as: :xiaozhi_news
  match '/chouti/feed/' => 'posts#chouti_feed', via: :get, defaults: { format: :rss }
  match '/chouti/(:url_code)' => 'posts#chouti_news', via: :get, as: :chouti_news
  match '/coop/:coop/feed/' => 'posts#coop_feed', via: :get, defaults: { format: :rss }
  match '/coop/:coop/(:url_code).html' => 'posts#coop_news', via: :get
  match '/crop/:partner/feed' => 'posts#partner_feed', via: :get, defaults: { format: :rss }

  match '/newsflash/coop/:coop/feed/' => 'newsflashes#news_corp_feed', via: :get, defaults: { format: :rss }
  match '/newsflash/coop/(:id).html' => 'newsflashes#news_corp_news', via: :get

  match '/uc/feed/' => 'posts#uc_feed', via: :get, defaults: { format: :rss }
  match '/uc/(:url_code)' => 'posts#ucnews', via: :get, as: :uc_news
  match '/p/(:url_code)(.:format)' => 'posts#show', via: :get, constraints: { format: '' }
  match '/p/preview/(:key).html' => 'posts#preview', via: :get, as: :preview_post_by_key
  match '/feed/bdnews_feed_d9rIUTwdPm' => 'posts#feed_bdnews', via: :get, defaults: { format: :rss }
  match '/feed/:params(.:format)' => redirect('/feed'), via: :get
  match '/feed(/:params)' => 'posts#feed', via: :get, defaults: { format: :rss }, as: :feed
  match '/tag/:tag', :controller => 'tags', :action => 'show', via: :get, as: :tag
  match '/clipped/:year/:month/:day', :controller => 'newsflashes', :action => 'index', via: :get, as: :newsflashes_of_day
  match '/clipped/feed/', :controller => 'newsflashes', :action => 'feed', ptype: '_newsflash', via: :get, defaults: { format: :rss }
  match '/clipped/:id', :controller => 'newsflashes', :action => 'show', via: :get, as: :newsflash_show
  match '/clipped/:id/touch_view', :controller => 'newsflashes', :action => 'touch_view', via: :post, as: :newsflash_touch_view
  match '/clipped/touch_views', :controller => 'newsflashes', :action => 'touch_views', via: :post, as: :newsflash_touch_views
  match '/product_notes', :controller => 'newsflashes', :action => 'product_notes', ptype: '_pdnote', via: :get, as: :product_notes
  match '/product_notes/feed/', :controller => 'newsflashes', :action => 'feed', ptype: '_pdnote', via: :get, defaults: { format: :rss }
  match '/newsflashes/', :controller => 'newsflashes', :action => 'newsflashes', ptype: '_newsflash', via: :get, as: :newsflashes_list
  match '/newsflashes/search', :controller => 'newsflashes', :action => 'search', via: :get, as: :newsflashes_search
  match '/changelog', :controller => 'welcome', :action => 'changes', via: :get, as: :changes
  match '/posts/article_toggle_tag', to: 'posts#article_toggle_tag', via: :post, as: :article_toggle_tag
  match '/newsflashes/toggle_tag', to: 'newsflashes#toggle_tag', via: :post, as: :newsflash_toggle_tag
  match '/posts/:user_domain', to: 'users#posts', via: :get, as: :user_domain_posts
  match '/newsflashes/change_switch_state', :controller => 'newsflashes', :action => 'change_switch_state', via: :post, as: :newsflashes_change_switch_state

  # 兼容老站，添加特定的URL映射
  match '/about' => redirect('/pages/about'), via: :get
  match '/hire' => redirect('/pages/hire'), via: :get
  match '/contribute' => redirect('/pages/contribute'), via: :get
  match '/ads' => redirect('/pages/ads'), via: :get
  match '/ad' => redirect('/pages/ads'), via: :get
  match '/account(/*any)' => redirect('/pages/app'), via: :get
  match '/api/site_map.:format' => "welcome#site_map", via: :get, constraints: { format: 'xml' }
  match '/api/site_map2.:format' => "welcome#site_map2", via: :get, constraints: { format: 'xml' }
  match '/api/wx.:format' => "search#search", via: :get, constraints: { format: 'xml' }
  match '/api/wx/column.:format' => "columns#show", via: :get, constraints: { format: 'xml' }
  match '/:year(/:month)(/:day)' => "posts#archives", via: :get, :constraints => { :year => /201\d{1}/, :month => /\d{1,2}/, :day => /\d{1,2}/ }, as: :post_archives

  %w(404 500).each do |code|
    match code, to: "errors#render_#{code}", via: [:get, :post, :put, :delete]
  end
end

app/controllers/search_controller.rb
require 'uri'
class SearchController < ApplicationController

  def search
    @data = Java::Search.search params
    @total_count = @data['data']['totalCount']
    @posts = @data['data']['article']

    respond_to do |format|
      format.html do
        if request.xhr?
          render 'search/_list', locals: { :posts => @posts }, layout: false
        end
      end
      format.xml do
        if @posts.length > 0
          #/api/wx.xml?q=ibm&to_user=toUser&from_user=fromUser&page=1&per_page=5
          render 'api/wx', locals: { :posts => @posts }, layout: false
        else
          render text: ''
        end
      end
    end

  end
  
  def search_ruby
    params[:q] = URI.unescape(params[:q]).gsub('/','') unless params[:q].blank?
    if params[:q].blank?
      @message = '搜索关键词不能为空'
      @posts = Post.none
    elsif params[:q].length > Settings.elasticsearch.query.max_length
      @message = '搜索关键词过长'
      @posts = Post.none
    else
      @posts = Post.search(params)
    end

    respond_to do |format|
      format.html do
        if request.xhr?
          render 'search/_list', locals: { :posts => @posts }, layout: false
        end
      end
      format.json do
        render json: Post.posts_to_json(@posts, true)
      end
      format.xml do
        if @posts.length > 0
          #/api/wx.xml?q=ibm&to_user=toUser&from_user=fromUser&page=1&per_page=5
          render 'api/wx', locals: { :posts => @posts }, layout: false
        else
          render text: ''
        end
      end
    end
    
  end

end

app/helpers/search_helper.rb
module SearchHelper
  def display_search_title(post, hit)
    return raw hit['highlight']['title'].first if hit['highlight']
    raw post.title
  end

  def display_search_newsflash_title(newflash, hit)
    return raw hit['highlight']['hash_title'].first if hit['highlight']
    raw newflash.hash_title
  end

  def show_post_url url_code
  	"#{Settings.site}/p/#{url_code}.html"
  end

end

app/views/search/_list.html.slim
- if @posts.present?
  - @posts.each do |post|
    - @index = (@index || 0) + 1
    article
      a.pic[data-fit-mobile="true" class="badge-#{post['slug']}" href="#{show_post_url post['id']}" data-lazyload="#{high_speed_url post['img'], 'feature'}" data-stat-click="Wenzhangtupian.#{@index}.#{post['id']}.click"]
      .desc
        a.title[href=show_post_url(post['id']) target="_blank" data-stat-click="Wenzhangbiaoti.#{@index}.#{post['id']}.click"]
          = raw post['highlight']
        .author
          a[href="/posts/#{post['author']['domain']}" data-stat-click="Wenzhangzuozhe.#{@index}.#{post['id']}.click"]
            span.avatar[data-lazyload="#{post['author']['avatar_url']}"]
            span.name
              = (post['author']['name'])
          span.time
            |&nbsp;•&nbsp;
            = smart_time_ago post['published_at'].to_time
        .brief
          = raw post['summary']

  = link_to '', search_path(q: params[:q], published_at: @posts.last['published_at'].to_time.to_i, format: :html), class: 'load-more J_listLoadMore', id: 'search_next_link', 'data-stat-click' => "wenzhanggengduo.click"

- elsif @message.present?
  article.search_none_info
     = @message
- else
  = link_to '', "javascript:void(0)", class: 'load-more J_listLoadMore no-data'

app/views/search/_list_ruby.html.slim
- if @posts.present?
  - @posts.each_with_hit do |post, hit|
    - @index = (@index || 0) + 1
    article
      a.pic[data-fit-mobile="true" class="badge-#{post.column.try(:slug)}" href="#{post_url(post, utm_source: utm_source ||= nil)}" data-lazyload="#{high_speed_url post.cover_real_url, 'feature'}" data-stat-click="Wenzhangtupian.#{@index}.#{post.url_code}.click"]
      .desc
        a.title[href=post_url(post, utm_source: 'site_search' ) target="_blank" data-stat-click="Wenzhangbiaoti.#{@index}.#{post.url_code}.click"]
          = display_search_title(post, hit)
        .author
          a[href="#{user_domain(post.author.try(:domain))}" data-stat-click="Wenzhangzuozhe.#{@index}.#{post.url_code}.click"]
            span.avatar[data-lazyload="#{post.author.avatar}"]
            span.name
              = (post.author && post.author.display_name)
          span.time
            |&nbsp;•&nbsp;
            = smart_time_ago post.published_at
        .brief
          = raw post.summary

  = link_to '', search_path(q: params[:q], d: 'next', b_url_code: @posts.results.last.url_code, format: :html), class: 'load-more J_listLoadMore', id: 'search_next_link', 'data-stat-click' => "wenzhanggengduo.click"

- elsif @message.present?
  article.search_none_info
     = @message
- else
  = link_to '', "javascript:void(0)", class: 'load-more J_listLoadMore no-data'

app/views/search/search.html.slim
= render 'welcome/title', title: "搜索: #{params[:q]}"
= render 'welcome/canonical', :raw_url => "http://36kr.com/search/#{params[:q]}"
= stylesheet_link_tag 'krx/search-result', media: 'all'
= render 'layouts/tag', deep_report_link: root_path, deep_report_active: 'false'

.search-result-wrap
  .main-section
    .result-list.J_resultListWrap
      .result-info
        .keyword
          em.highlight '#{truncate(params[:q])}'
          | 搜索结果
        .count
          |结果数：
          em.highlight = @posts.present? ? @posts.total_count : 0

      .article-list
        .articles.J_articleList data-stat-module="Sousuo"
          = render 'search/list'

    .index-side
      .fast-section.J_fastSection.mobile-hide
        = render 'welcome/aside'
        = render_cell :ads, :position_9

= render 'layouts/footer', subnavs: [["搜索: #{params[:q]}", search_path(q: params[:q])]]
= javascript_include_tag 'krx/search-result', media: 'all'
= render 'welcome/wechat_share'

app/views/search/search_ruby.html.slim
= render 'welcome/title', title: "搜索: #{params[:q]}"
= render 'welcome/canonical', :raw_url => "http://36kr.com/search/#{params[:q]}"
= stylesheet_link_tag 'krx/search-result', media: 'all'
= render 'layouts/tag', deep_report_link: root_path, deep_report_active: 'false'

.search-result-wrap
  .main-section
    .result-list.J_resultListWrap
      .result-info
        .keyword
          em.highlight '#{truncate(params[:q])}'
          | 搜索结果
        .count
          |结果数：
          em.highlight = @posts.present? ? @posts.total_count : 0

      .article-list
        .articles.J_articleList data-stat-module="Sousuo"
          = render 'search/list_ruby'

    .index-side
      .fast-section.J_fastSection.mobile-hide
        = render 'welcome/aside'
        = render_cell :ads, :position_9

= render 'layouts/footer', subnavs: [["搜索: #{params[:q]}", search_path(q: params[:q])]]
= javascript_include_tag 'krx/search-result', media: 'all'
= render 'welcome/wechat_share'