config/routes.rb
require 'sidekiq/web'

# TODO路由测试

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'welcome#index', defaults: { format: :html }
  get 'search', to: 'search#search'

  # TODO 所有的 only: [] 全部改成 namespace :users，去掉所有的 only, except
  resources :users, only: [] do
    get :messages, on: :collection
  end

  namespace :admin, path: '/krypton' do
    authenticate :user, lambda { |u| Ability.new(u, 'Admin').can? :manage, :sidekiq } do
      mount Sidekiq::Web => '/sidekiq'
    end
    root to: redirect('/krypton/dashboard')
    resources :dashboard, :pages
    resources :newsflashes do
      member do
        patch :set_top
        patch :set_down
      end
    end
    resources :users do
      member do
        put :speak
        put :shutup
      end
      resources :posts, only: [:index], on: :collection
    end
    resources :ads, :fragment_templates
    resources :sites do
      resources :columns, module: :sites do
        patch :update_order_nums, on: :collection
      end
    end
    resources :head_lines, except: [:show] do
      get :archives, on: :collection
      post :archive, on: :member
      post :publish, on: :member
    end
    resources :columns do
      resources :posts, only: [:index], on: :collection do
        get :reviewings, on: :collection
      end
    end
    namespace :posts do
      resources :columns
    end
    resources :posts do
      resources :comments, only: [:index], on: :collection
      resources :related_links
      get :reviewings, on: :collection
      get :myown, on: :collection
      get :draft, on: :collection
      get :publish, on: :member
      post :do_publish, on: :member
      post :undo_publish, on: :member
      post :toggle_tag, on: :member
    end
    resources :favorites
    resources :comments do
      member do
        post :set_excellent
        post :do_publish
        post :do_reject
        post :undo_publish
      end
      collection do
        post :batch_do_publish
        post :batch_undo_publish
        post :batch_do_reject
        post :batch_set_excellent
        post :batch_unset_excellent
        delete :batch_destroy
      end
    end
    resources :info_flows do
      member do
        get :columns_and_ads
        post :update_columns
        post :update_ads
        get :edit_columns
        get :edit_ads
        delete :destroy_column
        delete :destroy_ad
      end
    end
    resources :mobile_ads

    get 'tools/redis'
    post 'tools/redis_refresh'
    get 'tools/report'
    post 'tools/gen_post_report'
  end

  namespace :components do
    get '/next/collections', to: 'next#collections', as: :next_collections
    get 'pages/show', to: 'pages#show', as: :page_body
    get 'posts/show', to: 'posts#show', as: :post_body
  end

  namespace :asynces do
    resources :posts, only: [] do
      get :hots, on: :collection
      get :today, on: :collection
      get :record_post_manage_session_path, on: :collection
      resources :comments, :only => [:index, :create]
    end

    resources :comments, only: [] do
      get :excellents, on: :collection
    end

    resources :favorites, only: [:create]

    resources :related_links, only: [] do
      get :get_metas_info, on: :collection
    end

    resources :head_lines, only: [] do
      get :get_metas_info, on: :collection
    end

    resources :dashboard, only: [] do
      get :charts, on: :collection
      get :pandect, on: :collection
    end

    resources :newsflashes, only: [:index]
  end

  resources :pages, only: [:show], param: :slug do
    get :hire, on: :collection
  end

  match '/current_user.json', to: 'users#current', via: :get
  match '/current_user_favorites.json', to: 'users#favorites', via: :get
  match '/upadte_current_user.json', to: 'users#update_current', via: :post
  match '/cancel_favorites', to: 'users#cancel_favorites', via: :get
  match '/comments/excellents', :controller => 'comments', :action => 'execllents', via: :get
  match '/columns/:slug/feed', :controller => 'columns', :action => 'feed', via: :get, as: :column_feed, defaults: { format: :rss }
  match '/columns/:slug(/:page)', :controller => 'columns', :action => 'show', via: :get, as: :column_slug
  match '/category/:slug(/:page)', :controller => 'columns', :action => 'show', via: :get
  match '/p/(:url_code).html' => 'posts#show', via: :get, as: :post_show_by_url_code

  match '/baidu/feed/' => 'posts#baidu_feed', via: :get, defaults: { format: :rss }
  match '/baidu/(:url_code)' => 'posts#bdnews', via: :get, as: :post_bdnews
  match '/xiaozhi/feed/' => 'posts#xiaozhi_feed', via: :get, defaults: { format: :rss }
  match '/xiaozhi/(:url_code)' => 'posts#xiaozhi_news', via: :get, as: :xiaozhi_news
  match '/chouti/feed/' => 'posts#chouti_feed', via: :get, defaults: { format: :rss }
  match '/chouti/(:url_code)' => 'posts#chouti_news', via: :get, as: :chouti_news
  match '/coop/:coop/feed/' => 'posts#coop_feed', via: :get, defaults: { format: :rss }
  match '/coop/:coop/(:url_code).html' => 'posts#coop_news', via: :get
  match '/crop/:partner/feed' => 'posts#partner_feed', via: :get, defaults: { format: :rss }

  match '/newsflash/coop/:coop/feed/' => 'newsflashes#news_corp_feed', via: :get, defaults: { format: :rss }
  match '/newsflash/coop/(:id).html' => 'newsflashes#news_corp_news', via: :get

  match '/uc/feed/' => 'posts#uc_feed', via: :get, defaults: { format: :rss }
  match '/uc/(:url_code)' => 'posts#ucnews', via: :get, as: :uc_news
  match '/p/(:url_code)(.:format)' => 'posts#show', via: :get, constraints: { format: '' }
  match '/p/preview/(:key).html' => 'posts#preview', via: :get, as: :preview_post_by_key
  match '/feed/bdnews_feed_d9rIUTwdPm' => 'posts#feed_bdnews', via: :get, defaults: { format: :rss }
  match '/feed/:params(.:format)' => redirect('/feed'), via: :get
  match '/feed(/:params)' => 'posts#feed', via: :get, defaults: { format: :rss }, as: :feed
  match '/tag/:tag', :controller => 'tags', :action => 'show', via: :get, as: :tag
  match '/clipped/:year/:month/:day', :controller => 'newsflashes', :action => 'index', via: :get, as: :newsflashes_of_day
  match '/clipped/feed/', :controller => 'newsflashes', :action => 'feed', ptype: '_newsflash', via: :get, defaults: { format: :rss }
  match '/clipped/:id', :controller => 'newsflashes', :action => 'show', via: :get, as: :newsflash_show
  match '/clipped/:id/touch_view', :controller => 'newsflashes', :action => 'touch_view', via: :post, as: :newsflash_touch_view
  match '/clipped/touch_views', :controller => 'newsflashes', :action => 'touch_views', via: :post, as: :newsflash_touch_views
  match '/product_notes', :controller => 'newsflashes', :action => 'product_notes', ptype: '_pdnote', via: :get, as: :product_notes
  match '/product_notes/feed/', :controller => 'newsflashes', :action => 'feed', ptype: '_pdnote', via: :get, defaults: { format: :rss }
  match '/newsflashes/', :controller => 'newsflashes', :action => 'newsflashes', ptype: '_newsflash', via: :get, as: :newsflashes_list
  match '/newsflashes/search', :controller => 'newsflashes', :action => 'search', via: :get, as: :newsflashes_search
  match '/changelog', :controller => 'welcome', :action => 'changes', via: :get, as: :changes
  match '/posts/article_toggle_tag', to: 'posts#article_toggle_tag', via: :post, as: :article_toggle_tag
  match '/newsflashes/toggle_tag', to: 'newsflashes#toggle_tag', via: :post, as: :newsflash_toggle_tag
  match '/posts/:user_domain', to: 'users#posts', via: :get, as: :user_domain_posts
  match '/newsflashes/change_switch_state', :controller => 'newsflashes', :action => 'change_switch_state', via: :post, as: :newsflashes_change_switch_state

  # 兼容老站，添加特定的URL映射
  match '/about' => redirect('/pages/about'), via: :get
  match '/hire' => redirect('/pages/hire'), via: :get
  match '/contribute' => redirect('/pages/contribute'), via: :get
  match '/ads' => redirect('/pages/ads'), via: :get
  match '/ad' => redirect('/pages/ads'), via: :get
  match '/account(/*any)' => redirect('/pages/app'), via: :get
  match '/api/site_map.:format' => "welcome#site_map", via: :get, constraints: { format: 'xml' }
  match '/api/site_map2.:format' => "welcome#site_map2", via: :get, constraints: { format: 'xml' }
  match '/api/wx.:format' => "search#search", via: :get, constraints: { format: 'xml' }
  match '/api/wx/column.:format' => "columns#show", via: :get, constraints: { format: 'xml' }
  match '/:year(/:month)(/:day)' => "posts#archives", via: :get, :constraints => { :year => /201\d{1}/, :month => /\d{1,2}/, :day => /\d{1,2}/ }, as: :post_archives

  %w(404 500).each do |code|
    match code, to: "errors#render_#{code}", via: [:get, :post, :put, :delete]
  end
end

app/models/info_flow.rb
# == Schema Information
#
# Table name: info_flows
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class InfoFlow < ActiveRecord::Base
  validates :name, presence: true
  validates_uniqueness_of :name

  has_and_belongs_to_many :columns
  has_and_belongs_to_many :ads

  after_save :update_info_flows_cache
  after_destroy :destroy_info_flows_cache

  DEFAULT_INFOFLOW = Settings.default_info_flow

  ###
  # options[:page]
  # options[:per_page]
  # options[:page_direction]
  # options[:boundary_post_url_code]
  # options[:ads_required]
  # options[:newsflash_required]
  ###
  def posts_with_ads(options = {})

    boundary_post = Post.find_by_url_code(options[:boundary_post_url_code]) if options[:boundary_post_url_code].present?

    # options[:page] = 1 if(options[:page_direction].present? && boundary_post.present?)
    posts = Post.where(:column_id => columns).published
    if options[:page_direction] == 'next' && boundary_post.present?
      posts = posts.where('posts.published_at < ?', boundary_post.published_at)
    elsif options[:page_direction] == 'prev' && boundary_post.present?
      posts = posts.where('posts.published_at > ?', boundary_post.published_at)
    end
    posts = posts.includes(:column, :related_links, author: [:krypton_authentication]).recent.page(options[:page] || 1).per(options[:per_page] || 30)
    posts_with_associations = get_associations_of(posts)

    if options[:newsflash_required]
      posts_with_associations = mix_posts_and_newsflashes posts_with_associations, options[:boundary_post_url_code], boundary_post
    end

    if options[:ads_required]
      ads = get_ads_with_period_of posts
      flow = mix_posts_and_ads posts_with_associations, ads
    else
      flow = posts_with_associations
    end

    { posts: flow,
      total_count: posts.total_count,
      prev_page: posts.prev_page,
      next_page: posts.next_page,
      first_url_code: (posts.first ? posts.first.url_code : nil),
      last_url_code: (posts.last ? posts.last.url_code : nil)
     }
  end

  def update_info_flows_cache
    logger.info "perform the worker to update info flows of #{name}"
    InfoFlowsComponentWorker.new.perform(name)
    true
  end

  def posts(options = {})
    options[:page_num] ||= 1
    options[:per_page] ||= Settings.site_map.posts_count
    Post.where(:column_id => columns).published.includes(:author, :column).order('published_at desc').page(options[:page_num]).per(options[:per_page])
  end

  private

  def get_associations_of(posts)
    JSON.parse posts.to_json(
      :except => [:content],
      :methods => [:cover_real_url, :comments_counts],
      :include => {
        :related_links => {
          },
        :author => {
          :only => [:id, :domain, :sso_id, :email, :phone, :role], :methods => [:display_name, :avatar] },
        :column => {
          :only => [:id, :name, :slug] }
        }
      )
  end

  def get_associations_of_newsflashes(newsflashes)
    JSON.parse newsflashes.to_json(
      :methods => [:news_url_type],
      :include => {
        :author => {
          :only => [:id, :domain, :sso_id, :email, :phone, :role], :methods => [:display_name, :avatar] },
        :column => {
          :only => [:id, :name, :slug] }
        }
      )
  end

  def get_ads_with_period_of(posts)
    post_begin = posts.offset_value
    post_end = [posts.current_page * posts.limit_value, posts.total_count].min
    ads = self.ads.where(:position => post_begin..post_end).order('position desc')
    ads.collect { |ad| ad.position -= post_begin; ad } # 减去分页造成的偏移
  end

  def mix_posts_and_ads(posts, ads)
    posts_mix = posts.dup.to_a
    ads.each do |ad|
      posts_mix.insert(ad.position, ad)
    end
    posts_mix
  end

  def mix_seperate_by_date(flow, posts)
    return [] if posts.blank?
    current_date = posts.first.created_at.strftime('%F')
    flow.each_with_index do |item, index|
      if item.class.to_s == 'Post' && item.created_at.strftime('%F') != current_date
        current_date = item.created_at.strftime('%F')
        flow.insert(index, { :date => current_date, :type => 'seperate' })
      end
    end
    flow
  end

  def mix_posts_and_newsflashes(posts, paginate_by_id_request, boundary_post)
    start_time = posts.present? ? posts.last['published_at'] : Time.parse('2000-01-01')
    if paginate_by_id_request.present?
      if posts.present?
        end_time = posts.first['published_at']
      elsif boundary_post.present?
        end_time = boundary_post.published_at
      else
        return posts
      end
    else
      end_time   = Time.now
    end
    newsflashes  = Newsflash.tagged_with('_newsflash').where(:column_id => columns).to_info_flow.where(created_at: start_time..end_time)
    newsflashes_with_assoicatio = get_associations_of_newsflashes(newsflashes)
    result       = posts + newsflashes_with_assoicatio
    result.sort do |a, b|
      get_object_time(b) <=> get_object_time(a)
    end
  end

  def destroy_info_flows_cache
    Redis::HashKey.new('info_flow_new').delete(name)
  end

  def get_object_time(obj)
    obj['published_at'].present? ? obj['published_at'] : obj['created_at']
  end
end

app/controllers/admin/info_flows_controller.rb
class Admin::InfoFlowsController < Admin::BaseController
  load_and_authorize_resource

  def index
    @info_flows = InfoFlow.order('created_at desc').page params[:page]
  end

  def update
    @info_flow.update(info_flow_params)
    respond_with @info_flow, location: admin_info_flows_path
  end

  def create
    @info_flow.save
    respond_with @info_flow, location: admin_info_flows_path
  end

  def destroy
    @info_flow.destroy
    redirect_to :back
  end

  def columns_and_ads
    @columns = @info_flow.columns
    @ads = @info_flow.ads
  end

  def edit_columns
    @columns_in_info_flow = @info_flow.columns
    @columns = Column.all - @columns_in_info_flow
  end

  def edit_ads
    @ads_in_info_flow = @info_flow.ads.order('position')
    @ads = Ad.all.order('position') - @ads_in_info_flow
  end

  def update_columns
    update_association('columns', params['column_ids']) if params[:column_ids]
  end

  def update_ads
    update_association('ads', params['ad_ids']) if params[:ad_ids]
  end

  def destroy_column
    destroy_association('columns', params[:column_id])
    redirect_to columns_and_ads_admin_info_flow_path(@info_flow)
  end

  def destroy_ad
    destroy_association('ads', params[:ad_id])
    redirect_to columns_and_ads_admin_info_flow_path(@info_flow, anchor: 'info_flow_ads')
  end

  private

  def destroy_association(associations, id)
    @obj = associations.chop.classify.constantize.find(id)
    @info_flow.send(associations.to_sym).send(:delete, @obj)
    @info_flow.update_info_flows_cache
  end

  def update_association(associations, ids)
    ActiveRecord::Base.transaction do
      @obj = associations.chop.classify.constantize
      @info_flow.send associations.concat('=').to_sym, @obj.where(id: ids)
      @info_flow.update_info_flows_cache
    end
    render :json => { 'result' => 'sucess' }
  end

  def info_flow_params
    params.require(:info_flow).permit(:name) if params[:info_flow]
  end
end

app/views/admin/info_flows/_ad.html.slim
- @ads.each do |ad|
  tr
    td = ad.id
    td = ad.position
    td = ad.content
    td = ad.created_at
    td
      a title="删除" data-method="delete" data-confirm="确定删除该广告位 ？" href= destroy_ad_admin_info_flow_path(@info_flow, ad_id:ad)
        i.fa.fa-times

app/views/admin/info_flows/_ads.html.slim
= link_to "+  关联广告位", edit_ads_admin_info_flow_path(@info_flow), class:"btn btn-primary guanlian"

div.widget-box
  div class="widget-content nopadding"
    - if @ads.present?
      table class="table"
        thead
          tr role="row"
            th ID
            th 广告位
            th 内容
            th 操作
        tbody
          = render 'ad'
    - else
      p.text_center 暂无内容....

app/views/admin/info_flows/_columns.html.slim
= link_to "+  关联专栏", edit_columns_admin_info_flow_path(@info_flow), class:"btn btn-primary guanlian"

div.widget-box
  div class="widget-content"
    ul.thumbnails
      - @columns.each do |column|
        li.col-lg-2
          a href=  admin_column_posts_path(column)
            - if column.icon_url
              img onerror="imgError(this)" src="#{column.icon_url}"
            - else
             p.default-cover
               span 专栏
          div.descripiton
            h5  = column.name
          span class="label label-danger" data-placement="left" title="文章数"  = column.posts_count.to_i

app/views/admin/info_flows/_info_flow.html.slim
tr
  td = info_flow.id
  td = link_to info_flow.name, columns_and_ads_admin_info_flow_path(info_flow)
  td = info_flow.created_at.to_s(:db)
  td.text_center
    a title="详情" href= columns_and_ads_admin_info_flow_path(info_flow)
      i.fa.fa-plus-circle
    |&nbsp;&nbsp;
    a title="编辑" href= edit_admin_info_flow_path(info_flow)
      i.fa.fa-pencil
    |&nbsp;&nbsp;
    a title="删除" data-method="delete" data-confirm="确定删除该广告位 ？" href= admin_info_flow_path(info_flow)
      i.fa.fa-times

app/views/admin/info_flows/columns_and_ads.html.slim
= render 'welcome/title', title: "#{@info_flow.name}"

.col_main.widget-box
  .main_hd
    h2 &nbsp;
    .toolbar.clearfix.new
      .pull-right style="margin-top: 40px;"
        i.fa.fa-map-marker
        ol.breadcrumb
          li = link_to '信息流管理', admin_info_flows_path
          li.active
            = @info_flow.name
            | 信息流
    div.widget-title
      ul class="nav nav-tabs"
        li.active
          a data-toggle="tab" href="#info_flow_columns"  专栏
        li
          a data-toggle="tab" href="#info_flow_ads"  广告位
  .main-body
    div class="widget-content tab-content"
      div#info_flow_columns class="tab-pane active"
        = render 'columns'
      div#info_flow_ads class="tab-pane"
        = render 'ads'


    javascript:
      $(document).ready(function(){
        if(window.location.hash != "")
          $("a[href='"+ window.location.hash +"']").click();
      });

app/views/admin/info_flows/edit_ads.html.slim
= render 'welcome/title', title: '关联广告位'

.col_main
  .main_hd
    h2 信息流管理
    .toolbar.border_bottom.clearfix.new
      .pull-right
        i.fa.fa-map-marker
        ol.breadcrumb
          li = link_to '信息流管理', admin_info_flows_path
          li = link_to "#{@info_flow.name}信息流", columns_and_ads_admin_info_flow_path(@info_flow)
          li.active 关联广告位
  .main-body
    div.container-fluid
      div.widget-box
        div clas="widget-content" style="padding:20px;"
          select id="custom-multiselect-headers" multiple="multiple"
            - @ads_in_info_flow.each do |ad|
                option value="#{ad.id}" selected="selected"  ="广告位：#{ad.position}"
            - @ads.each do |ad|
                option value="#{ad.id}"  ="广告位：#{ad.position}"
          div.actions style="margin-top:20px;  text-align: center;"
            button#multiselect-refresh class="btn btn-success" 重置
            button#multiselect-submit class="btn btn-primary" style="margin-left:20px;" 保存修改
javascript:
  $(document).ready(function(){
    $('#custom-multiselect-headers').multiSelect({
      keepOrder: true,
      selectableHeader: "<input type='text' class='search-input search-input-header' autocomplete='off' placeholder='待选广告位'>",
      selectionHeader:  "<input type='text' class='search-input search-input-header' autocomplete='off' placeholder='已选广告位'>",
      afterInit: function(ms){
        var that = this,
            $selectableSearch = that.$selectableUl.prev(),
            $selectionSearch = that.$selectionUl.prev(),
            selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
            selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

        that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
        .on('keydown', function(e){
          if (e.which === 40){
            that.$selectableUl.focus();
            return false;
          }
        });

        that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
        .on('keydown', function(e){
          if (e.which == 40){
            that.$selectionUl.focus();
            return false;
          }
        });
      },
      afterSelect: function(){
        this.qs1.cache();
        this.qs2.cache();
      },
      afterDeselect: function(){
        this.qs1.cache();
        this.qs2.cache();
      }
    });

    $('#multiselect-refresh').on('click', function(){
      location.reload();
    });

     $('#multiselect-submit').on('click', function(){
       ids = $('#custom-multiselect-headers').val();
       $.ajax({
         "url": "#{update_ads_admin_info_flow_path(@info_flow)}",
         "data": {'ad_ids':ids},
         "dataType": "json",
         "type": "POST",
         "success": function () {
           window.location = "#{columns_and_ads_admin_info_flow_path(@info_flow, anchor:'info_flow_ads')}";
         }
      });
    });
  });

app/views/admin/info_flows/edit_columns.html.slim
= render 'welcome/title', title: '关联专栏'

.col_main
  .main_hd
    h2 信息流管理
    .toolbar.border_bottom.clearfix.new
      .pull-right
        i.fa.fa-map-marker
        ol.breadcrumb
          li = link_to '信息流管理', admin_info_flows_path
          li = link_to "#{@info_flow.name}信息流", columns_and_ads_admin_info_flow_path(@info_flow)
          li.active 关联专栏
  .main-body
    div.container-fluid
      div.widget-box
        div clas="widget-content" style="padding:20px;"
          select id="custom-multiselect-headers" multiple="multiple"
            - @columns_in_info_flow.each do |column|
                option value="#{column.id}" selected="selected"  ="#{column.name}"
            - @columns.each do |column|
                option value="#{column.id}"  ="#{column.name}"
          div.actions style="margin-top:20px; text-align: center;"
            button#multiselect-refresh class="btn btn-success" 重置
            button#multiselect-submit class="btn btn-primary" style="margin-left:20px;" 保存修改



javascript:
  $(document).ready(function(){
    $('#custom-multiselect-headers').multiSelect({
      keepOrder: true,
      selectableHeader: "<input type='text' class='search-input search-input-header' autocomplete='off' placeholder='待选专栏'>",
      selectionHeader:  "<input type='text' class='search-input search-input-header' autocomplete='off' placeholder='已选专栏'>",
      afterInit: function(ms){
        var that = this,
            $selectableSearch = that.$selectableUl.prev(),
            $selectionSearch = that.$selectionUl.prev(),
            selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
            selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

        that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
        .on('keydown', function(e){
          if (e.which === 40){
            that.$selectableUl.focus();
            return false;
          }
        });

        that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
        .on('keydown', function(e){
          if (e.which == 40){
            that.$selectionUl.focus();
            return false;
          }
        });
      },
      afterSelect: function(){
        this.qs1.cache();
        this.qs2.cache();
      },
      afterDeselect: function(){
        this.qs1.cache();
        this.qs2.cache();
      }
    });

    $('#multiselect-refresh').on('click', function(){
      location.reload();
    });

     $('#multiselect-submit').on('click', function(){
       ids = $('#custom-multiselect-headers').val();
       $.ajax({
         "url": "#{update_columns_admin_info_flow_path(@info_flow)}",
         "data": {'column_ids':ids},
         "dataType": "json",
         "type": "POST",
         "success": function () {
           window.location = "#{columns_and_ads_admin_info_flow_path(@info_flow)}";
         }
      });
    });
  });

app/views/admin/info_flows/index.html.slim
= render 'welcome/title', title: '信息流管理'

.col_main
  .main_hd
    h2 信息流管理
    .toolbar.border_bottom.clearfix
      .pull-right
         span.page_info = page_entries_info @info_flows
         = link_to raw("<i class='fa fa-plus'></i>&nbsp;&nbsp;创建信息流"), new_admin_info_flow_path, class:"btn btn-primary"
  table class="table"
    thead
      tr role="row"
        th ID
        th 名称
        th 创建时间
        th.text_center 操作
    tbody
      = render @info_flows
  = paginate @info_flows

app/views/admin/info_flows/new.html.slim
= render 'welcome/title', title: '信息流管理'

.col_main
  .main_hd
    h2 信息流管理
    .toolbar.border_bottom.clearfix.new
      .pull-right
        i.fa.fa-map-marker
        ol.breadcrumb
          li = link_to '信息流管理', admin_info_flows_path
          li.active 创建信息流
  .main-body
    = simple_form_for [:admin, @info_flow], html:{class:"form-horizontal"} do | f |
      = f.input :name
      div.form-actions
        = f.button :submit, data: { disable_with: "Submitting..." }, class:"btn btn-primary"