config/routes.rb
require 'sidekiq/web'

# TODO路由测试

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'welcome#index', defaults: { format: :html }
  get 'search', to: 'search#search'

  # TODO 所有的 only: [] 全部改成 namespace :users，去掉所有的 only, except
  resources :users, only: [] do
    get :messages, on: :collection
  end

  namespace :admin, path: '/krypton' do
    authenticate :user, lambda { |u| Ability.new(u, 'Admin').can? :manage, :sidekiq } do
      mount Sidekiq::Web => '/sidekiq'
    end
    root to: redirect('/krypton/dashboard')
    resources :dashboard, :pages
    resources :newsflashes do
      member do
        patch :set_top
        patch :set_down
      end
    end
    resources :users do
      member do
        put :speak
        put :shutup
      end
      resources :posts, only: [:index], on: :collection
    end
    resources :ads, :fragment_templates
    resources :sites do
      resources :columns, module: :sites do
        patch :update_order_nums, on: :collection
      end
    end
    resources :head_lines, except: [:show] do
      get :archives, on: :collection
      post :archive, on: :member
      post :publish, on: :member
    end
    resources :columns do
      resources :posts, only: [:index], on: :collection do
        get :reviewings, on: :collection
      end
    end
    namespace :posts do
      resources :columns
    end
    resources :posts do
      resources :comments, only: [:index], on: :collection
      resources :related_links
      get :reviewings, on: :collection
      get :myown, on: :collection
      get :draft, on: :collection
      get :publish, on: :member
      post :do_publish, on: :member
      post :undo_publish, on: :member
      post :toggle_tag, on: :member
    end
    resources :favorites
    resources :comments do
      member do
        post :set_excellent
        post :do_publish
        post :do_reject
        post :undo_publish
      end
      collection do
        post :batch_do_publish
        post :batch_undo_publish
        post :batch_do_reject
        post :batch_set_excellent
        post :batch_unset_excellent
        delete :batch_destroy
      end
    end
    resources :info_flows do
      member do
        get :columns_and_ads
        post :update_columns
        post :update_ads
        get :edit_columns
        get :edit_ads
        delete :destroy_column
        delete :destroy_ad
      end
    end
    resources :mobile_ads

    get 'tools/redis'
    post 'tools/redis_refresh'
    get 'tools/report'
    post 'tools/gen_post_report'
  end

  namespace :components do
    get '/next/collections', to: 'next#collections', as: :next_collections
    get 'pages/show', to: 'pages#show', as: :page_body
    get 'posts/show', to: 'posts#show', as: :post_body
  end

  namespace :asynces do
    resources :posts, only: [] do
      get :hots, on: :collection
      get :today, on: :collection
      get :record_post_manage_session_path, on: :collection
      resources :comments, :only => [:index, :create]
    end

    resources :comments, only: [] do
      get :excellents, on: :collection
    end

    resources :favorites, only: [:create]

    resources :related_links, only: [] do
      get :get_metas_info, on: :collection
    end

    resources :head_lines, only: [] do
      get :get_metas_info, on: :collection
    end

    resources :dashboard, only: [] do
      get :charts, on: :collection
      get :pandect, on: :collection
    end

    resources :newsflashes, only: [:index]
  end

  resources :pages, only: [:show], param: :slug do
    get :hire, on: :collection
  end

  match '/current_user.json', to: 'users#current', via: :get
  match '/current_user_favorites.json', to: 'users#favorites', via: :get
  match '/upadte_current_user.json', to: 'users#update_current', via: :post
  match '/cancel_favorites', to: 'users#cancel_favorites', via: :get
  match '/comments/excellents', :controller => 'comments', :action => 'execllents', via: :get
  match '/columns/:slug/feed', :controller => 'columns', :action => 'feed', via: :get, as: :column_feed, defaults: { format: :rss }
  match '/columns/:slug(/:page)', :controller => 'columns', :action => 'show', via: :get, as: :column_slug
  match '/category/:slug(/:page)', :controller => 'columns', :action => 'show', via: :get
  match '/p/(:url_code).html' => 'posts#show', via: :get, as: :post_show_by_url_code

  match '/baidu/feed/' => 'posts#baidu_feed', via: :get, defaults: { format: :rss }
  match '/baidu/(:url_code)' => 'posts#bdnews', via: :get, as: :post_bdnews
  match '/xiaozhi/feed/' => 'posts#xiaozhi_feed', via: :get, defaults: { format: :rss }
  match '/xiaozhi/(:url_code)' => 'posts#xiaozhi_news', via: :get, as: :xiaozhi_news
  match '/chouti/feed/' => 'posts#chouti_feed', via: :get, defaults: { format: :rss }
  match '/chouti/(:url_code)' => 'posts#chouti_news', via: :get, as: :chouti_news
  match '/coop/:coop/feed/' => 'posts#coop_feed', via: :get, defaults: { format: :rss }
  match '/coop/:coop/(:url_code).html' => 'posts#coop_news', via: :get
  match '/crop/:partner/feed' => 'posts#partner_feed', via: :get, defaults: { format: :rss }

  match '/newsflash/coop/:coop/feed/' => 'newsflashes#news_corp_feed', via: :get, defaults: { format: :rss }
  match '/newsflash/coop/(:id).html' => 'newsflashes#news_corp_news', via: :get

  match '/uc/feed/' => 'posts#uc_feed', via: :get, defaults: { format: :rss }
  match '/uc/(:url_code)' => 'posts#ucnews', via: :get, as: :uc_news
  match '/p/(:url_code)(.:format)' => 'posts#show', via: :get, constraints: { format: '' }
  match '/p/preview/(:key).html' => 'posts#preview', via: :get, as: :preview_post_by_key
  match '/feed/bdnews_feed_d9rIUTwdPm' => 'posts#feed_bdnews', via: :get, defaults: { format: :rss }
  match '/feed/:params(.:format)' => redirect('/feed'), via: :get
  match '/feed(/:params)' => 'posts#feed', via: :get, defaults: { format: :rss }, as: :feed
  match '/tag/:tag', :controller => 'tags', :action => 'show', via: :get, as: :tag
  match '/clipped/:year/:month/:day', :controller => 'newsflashes', :action => 'index', via: :get, as: :newsflashes_of_day
  match '/clipped/feed/', :controller => 'newsflashes', :action => 'feed', ptype: '_newsflash', via: :get, defaults: { format: :rss }
  match '/clipped/:id', :controller => 'newsflashes', :action => 'show', via: :get, as: :newsflash_show
  match '/clipped/:id/touch_view', :controller => 'newsflashes', :action => 'touch_view', via: :post, as: :newsflash_touch_view
  match '/clipped/touch_views', :controller => 'newsflashes', :action => 'touch_views', via: :post, as: :newsflash_touch_views
  match '/product_notes', :controller => 'newsflashes', :action => 'product_notes', ptype: '_pdnote', via: :get, as: :product_notes
  match '/product_notes/feed/', :controller => 'newsflashes', :action => 'feed', ptype: '_pdnote', via: :get, defaults: { format: :rss }
  match '/newsflashes/', :controller => 'newsflashes', :action => 'newsflashes', ptype: '_newsflash', via: :get, as: :newsflashes_list
  match '/newsflashes/search', :controller => 'newsflashes', :action => 'search', via: :get, as: :newsflashes_search
  match '/changelog', :controller => 'welcome', :action => 'changes', via: :get, as: :changes
  match '/posts/article_toggle_tag', to: 'posts#article_toggle_tag', via: :post, as: :article_toggle_tag
  match '/newsflashes/toggle_tag', to: 'newsflashes#toggle_tag', via: :post, as: :newsflash_toggle_tag
  match '/posts/:user_domain', to: 'users#posts', via: :get, as: :user_domain_posts
  match '/newsflashes/change_switch_state', :controller => 'newsflashes', :action => 'change_switch_state', via: :post, as: :newsflashes_change_switch_state

  # 兼容老站，添加特定的URL映射
  match '/about' => redirect('/pages/about'), via: :get
  match '/hire' => redirect('/pages/hire'), via: :get
  match '/contribute' => redirect('/pages/contribute'), via: :get
  match '/ads' => redirect('/pages/ads'), via: :get
  match '/ad' => redirect('/pages/ads'), via: :get
  match '/account(/*any)' => redirect('/pages/app'), via: :get
  match '/api/site_map.:format' => "welcome#site_map", via: :get, constraints: { format: 'xml' }
  match '/api/site_map2.:format' => "welcome#site_map2", via: :get, constraints: { format: 'xml' }
  match '/api/wx.:format' => "search#search", via: :get, constraints: { format: 'xml' }
  match '/api/wx/column.:format' => "columns#show", via: :get, constraints: { format: 'xml' }
  match '/:year(/:month)(/:day)' => "posts#archives", via: :get, :constraints => { :year => /201\d{1}/, :month => /\d{1,2}/, :day => /\d{1,2}/ }, as: :post_archives

  %w(404 500).each do |code|
    match code, to: "errors#render_#{code}", via: [:get, :post, :put, :delete]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  authorize_object :welcome

  def index
    return cache_index if (params[:page].blank? || params[:page].to_i == 1) && !paginate_by_id_request?
    info_flow = InfoFlow.find_by_name InfoFlow::DEFAULT_INFOFLOW

    posts_with_ads = info_flow.posts_with_ads(page: params[:page], page_direction: params[:d], boundary_post_url_code: params[:b_url_code], ads_required: false, newsflash_required: true)

    @posts_with_ads = posts_with_ads[:posts]
    @total_count = posts_with_ads[:total_count]
    @first_url_code = posts_with_ads[:first_url_code]
    @last_url_code = posts_with_ads[:last_url_code]

    render_template
  end

  def cache_index
    flow_data = CacheClient.instance.info_flow
    cache_data = flow_data.blank? ? {} : JSON.parse(flow_data)
    @posts_with_ads = cache_data['posts']
    @first_url_code = cache_data['first_url_code']
    @last_url_code = cache_data['last_url_code']

    render_template
  end

  def changes
    change_content = File.read(File.expand_path('../../../doc/changes.md', __FILE__))
    @changes = GitHub::Markdown.render_gfm(change_content).html_safe
  end

  def site_map
    info_flow = InfoFlow.find_by_name InfoFlow::DEFAULT_INFOFLOW
    @posts = info_flow.posts
    @authors = User.recent_editor
    @columns = Column.headers
    @newsflashs = Newsflash.recent
  end

  def site_map2
    @tags = ActsAsTaggableOn::Tag.all.order('taggings_count desc')
  end

  private

  def paginate_by_id_request?
    params[:d].present? && params[:b_url_code].present?
  end

  def render_template
     respond_to do |format|
      format.json do
        render json: {
          :total_count => @total_count,
          :first_url_code => @first_url_code,
          :last_url_code => @last_url_code,
          :posts => @posts_with_ads.select{|item| item['position'] == nil && item["type"] != 'seperate'}
        }
      end
      format.all do
        if request.xhr?
          render 'welcome/_info_flow_items.html', locals: {
            :posts_with_ads => @posts_with_ads,
            :first_url_code => @first_url_code,
            :last_url_code => @last_url_code
          }, layout: false
        else
          render 'index.html'
        end
      end
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def columns_header
    return @columns_header if @columns_header.present?
    columns_data = CacheClient.instance.columns_header
    @columns_header = JSON.parse(columns_data.present? ? columns_data : '{}')
  end

  def seo meta
    [ Nokogiri::HTML.fragment(meta).css('title').to_html, Nokogiri::HTML.fragment(meta).css('meta').to_html ]
  end
end

app/views/welcome/_aside.slim
.list.J_fastSectionList
  .tabs.J_fastSectionNavBar
    a.active.newsflashes_nav[href="#" name="fast" data-stat-click="Kuaixunmokuai.biaoti.click"]
      | 快讯
    a.next_nav[href="#" name="next" data-stat-click="NEXTmokuai.biaoti.click"]
      | NEXT
    a[href="#" name="feed" data-stat-click="Chuangyefeedmokuai.biaoti.click"]
      | 创业动态
  .wrap
    .panel.fast-news-panel data-stat-module="Kuaixunmokuai"
      .tags-box.mobile-hide
        = render_cell :newsflashes_list, :tags, num: 15, from: :welcome_newsflash_index_tags_cloud
      div
        = render_cell :newsflashes, :index
    .panel.next-panel style="display: none" data-stat-module="NEXTmokuai"
      .next-inner
      .next-link
        a href="http://next.36kr.com" target="_blank" data-stat-click="gengduo.click" OK，NEXT
    .panel.feed-panel.feed[style="display: none" data-stat-module="Chuangyefeedmokuai"]
      .feed-inner
      a.load-more href="#" data-stat-click="gengduo.click"

app/views/welcome/_canonical.html.erb
<% content_for :canonical do %>
  <link rel="canonical" href="<%= raw_url %>">
<% end %>

app/views/welcome/_header.html.slim
.news-list.J_articleListWrap data-stat-module="Zhufeed"
  .categories.J_newsListNavBar
    = link_to '全部', root_path, 'data-type' => 'all', class: "#{active_class('all', data_type)} #{ 'tab' unless tab_all_redirect }", id: 'column_header_all', 'data-stat-click' => "fenleiall.click"

    - columns && columns.each do |column|
      = link_to column["name"], column_slug_path(slug: column["slug"]), 'data-type' => column["slug"], class: "#{active_class(column["slug"], data_type)} tab", id: "column_header_#{column['slug']}", 'data-stat-click' => "fenlei#{column["slug"]}.click"

    = link_to '新产品', product_notes_path, 'data-type' => 'pdn', class: "#{active_class('pdn', data_type)} #{ 'tab' unless tab_all_redirect }", id: 'column_header_pdn', 'data-stat-click' => "fenleixinchanpin.click"
  = yield

app/views/welcome/_info_flow_items.html.slim
- if !!posts_with_ads && posts_with_ads.count > 0
  - posts_with_ads.each_with_index do |item, index|
    - if item['position'] == nil && item["type"] != 'seperate' && item["published_at"].present?
      = render 'info_flow_post', post: item, index: index
    - elsif item["position"] == nil && item["type"] != 'seperate' && item["hash_title"].present?
      = render 'info_flow_newsflash', newsflash: item, index: index
    - elsif item["position"] != nil && item["content"].present?
      = raw item["content"]

  = link_to '', root_path(d: 'next', b_url_code: @last_url_code, format: :html), class: 'load-more J_listLoadMore', id: 'info_flows_next_link', 'data-stat-click' => "wenzhanggengduo.click"
- else
  a.load-more.J_listLoadMore.no-data[href="javascript:void(0)"]

app/views/welcome/_info_flow_newsflash.html.slim
article.fast
  - if newsflash['cover'].present?
    a.pic.no-pinter[data-fit-mobile="true" class="badge-#{newsflash['column'] && newsflash['column']['slug']}" href="javascript:void(0)" data-lazyload="#{high_speed_url newsflash['cover'], 'feature'}" data-stat-click="kuaixuntupian.#{index.next}.#{newsflash['id']}.click"]
      span.mask-tags data-type="#{newsflash['column'] && newsflash['column']['slug']}"
        = newsflash['column'] && newsflash['column']['name']
  .desc
    a.title.no-pinter[href='javascript:void(0)' target="_blank"]
      |【快讯】
      = newsflash["hash_title"]
    .author
      a[href="#{user_domain((author = newsflash['author']) && author['domain'])}" data-stat-click="kuaixunzuozhe.#{index.next}.#{newsflash['id']}.click"]
        span.avatar[data-lazyload="#{(author=newsflash['author']) && author['avatar']}"]
        span.name
          = (author = newsflash['author']) && author['display_name']
      span.time
        |&nbsp;•&nbsp;
        = smart_time_ago Time.parse(newsflash['created_at']) if newsflash['created_at'].present?
    .brief
      = newsflash['description_text']
      - if newsflash['news_url'].present?
        a[href=newsflash['news_url'] target="_blank" rel="nofollow"]
          | [#{newsflash['news_url_type']}]

app/views/welcome/_info_flow_post.html.slim
article
  a.pic.info_flow_news_image[data-fit-mobile="true" class="badge-#{post["column"]["slug"]}" href="#{(post["title_link"].present? ? post["title_link"] : post_path(post["url_code"]))}" data-lazyload="#{(high_speed_url post["cover_real_url"], 'feature')}" data-stat-click="wenzhangtupian.#{index.next}.#{post['url_code']}.click"]
    span.mask-tags data-type="#{post["column"]["slug"]}"
      = post["column"]["name"]
  .desc
    a.title.info_flow_news_title[href=(post["title_link"].present? ? post["title_link"] : post_path(post["url_code"])) target="_blank" data-stat-click="wenzhangbiaoti.#{index.next}.#{post['url_code']}.click"]
      = raw post["title"]
    .author
      a[href="#{post['author'].present? ? user_domain(post['author']['domain']) : 'javascript:void(0)'}"]
        span.avatar[data-lazyload="#{post['author']['avatar']}" data-stat-click="wenzhangzuozhe.#{index.next}.#{post['url_code']}.click"]
        span.name
          = (post["author"] && post["author"]["display_name"]) || "匿名用户"
      span.time
        |&nbsp;•&nbsp;
        = smart_time_ago Time.parse(post["published_at"]) if post["published_at"].present?
    .brief
      = raw(post["summary"])

app/views/welcome/_list.html.erb
<div class="content">
  <a name="lastest_news"></a>
  <div class="content-wrapper">
    <h2 class="lastest">lastest news</h2>
    <div class="articles">
      <% posts_with_ads.each do |item| %>
        <% if item['position'] == nil && item["type"] != 'seperate' %>
          <article class="posts post-1 cf">
            <div class="info cf">
              <div class="topic left">
                <span>
                  <a class="<%= item["column"]["slug"] %>" href="/columns/<%= item["column"]["slug"] %>" > <%= item["column"]["name"] %> </a> / <%= item["column"]["slug"] %>
                </span>
              </div>
              <div class="postmeta right">
                <a href="javascript:void(0)"> <%= item["author"] && item["author"]["display_name"] %> </a>
                 •
                <abbr class="timeago" title="<%= item["created_at"]%>"><%= item["human_created_at"] %></abbr>
              </div>
            </div>
            <div class="post">
              <div class="left left-col">
                <div class="meta">
                  <a title="评论次数" href="<%= item["title_link"].present? ? item["title_link"] : post_url(item["url_code"]) %>" >
                    <i class="icon icon-share"></i>
                    <%= item["comments_counts"] || 0 %>
                  </a>
                </div>
                <div class="image feature-img thumb-180">
                  <a href="<%= item["title_link"].present? ? item["title_link"] : post_url(item["url_code"]) %>">
                    <img src="<%= item["cover_real_url"] %>" alt="" />
                  </a>
                </div>
              </div>
            </div>
            <div class="right-col">
              <h1>
                <a href="<%= item["title_link"].present? ? item["title_link"] : post_url(item["url_code"]) %>" target="new" ><%= raw item["title"] %></a>
              </h1>
              <p><%= raw(item["summary"]) %></p>
            </div>
          </article>
        <% elsif item["position"] != nil %>
          <%#= raw item["content"] %>
        <% end %>
      <% end if posts_with_ads.present? %>
    </div>
    <div class="pagination cf">
      <ul>
         <% if prev_page %>
           <li class="previous">
             <%= link_to '← 上一页', "/?page=#{prev_page}", rel:"prev", class:"left" %>
           </li>
         <% else %>
           <li class="previous disabled"><a href="#" class="left"><i class="icon-prev"></i>上一页</a></li>
         <% end %>
         <% if next_page %>
           <li class="next_page">
             <%= link_to '下一页 →', "/?page=#{next_page}", rel:"next", class:"right" if next_page %>
           </li>
         <% else %>
           <li class="next_page disabled"><a href="#" class="right"><i class="icon-next"></i>下一页</a></li>
         <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/welcome/_title.html.slim
- seo_metas_with_title ||= nil; title ||= nil
- seo_title, seo_metas = seo(seo_metas_with_title) if seo_metas_with_title.present?
- content_for :title do
  - if seo_title.present?
    = raw seo_title
  - else
    = content_tag :title, "#{title} | 36氪", s_t: onblur_title(title || '')
  - if seo_metas.present?
    = raw seo_metas
  - else
    meta name="keywords" content="36氪, 36kr, 36tr, 创业, 想创业, 投资, 融资, 创投媒体, 创业公司, 科技新闻, 移动互联网, 资讯平台, 开放日, 互联网创业"
    meta name="description" content="36氪是一个关注互联网创业的科技博客"

app/views/welcome/_wechat_share.html.slim
- share_title ||= nil
- share_desc  ||= nil
- share_img   ||= nil

javascript:
  $(document).ready(function(){
      // 微信分享
      var WEIXINSHARE = {
        shareTitle: '#{share_title}' || window.document.title,
        shareDesc: '#{share_desc}' || window.document.URL,
        shareImg: '#{share_img || "http://krplus-pic.b0.upaiyun.com/36kr_new_logo.jpg"}'
      };
      InitWeixinShare(WEIXINSHARE);
    });

app/views/welcome/changes.html.slim
= render 'welcome/title', title: '更新日志'

= stylesheet_link_tag 'krx/format', media: 'all'

.container style="margin: 0 auto;"
  article.single-post-article
    .content-wrapper-single
       section.article.changes-details
          = raw(@changes)

= render 'layouts/footer', subnavs: [['更新日志', changes_path]]
= render 'welcome/wechat_share', share_desc: '36氪是一个关注互联网创业的科技博客'

app/views/welcome/index.html.slim
= stylesheet_link_tag 'krx/index', media: 'all'
= render 'layouts/tag'

= render 'welcome/title', seo_metas_with_title: Redis::HashKey.new('www-home')[0]

.index-wrap
  - cache [:welcome, :head_line, Digest::SHA1.hexdigest((head_lines = CacheClient.instance.head_lines).to_s) ] do
    = render_cell :welcome, :head_line, head_lines: head_lines
  .main-section
    - cache [:welcome, :header_and_info_flows, columns_header.map{|c| c["updated_at"]}.max, Digest::SHA1.hexdigest(@posts_with_ads.to_s),  Digest::SHA1.hexdigest(head_lines.to_s)]
      = render layout: 'welcome/header', locals: { data_type: 'all', columns: columns_header, tab_all_redirect: false } do
        .article-list
          .articles.J_articleList
            = render_cell :welcome, :feed_top, head_lines: head_lines
            = render 'info_flow_items', :posts_with_ads => @posts_with_ads

    .index-side
      .fast-section.J_fastSection.mobile-hide
        = render 'welcome/aside'
        = render_cell :ads, :position_3

div.pre-load-ads
  div.J_channelAd.list-head-ad
    /!-- 广告位：频道定向广告－广告位 6
    script type="text/javascript" BAIDU_CLB_fillSlot("1091398")
  div.J_channelIndexAd.list-head-ad
    /!-- 广告位：信息流-全部-顶部广告位-广告位13
    script type="text/javascript" BAIDU_CLB_fillSlot("1116653")

= render 'layouts/footer'
= javascript_include_tag 'krx/index', media: 'all'
= render 'welcome/wechat_share', share_desc: '36氪是一个关注互联网创业的科技博客'